#import "base.typ": *
#show: setup.with(title: "Differential - M1 Problem statement", short: "M1 · Problem statement")

#title-block(
  title: [Differential: simulation-grounded AI diagnosis for analog audio electronics],
  subtitle: "Milestone 1 · Problem statement",
  meta: ("PRV 201 Frontiers of Technology (AI)", "Track A: Build", "Stevens Institute of Technology", "September 2026"),
)
*Executive summary.* When a tube preamplifier, studio console or vintage hi-fi unit fails, a technician must find which of its dozens to hundreds of parts failed; specialist shops we sampled charge \$125 to \$150 for that evaluation \[1, 2, 3\]. Differential assists the search. For a circuit it has a model of (@fig:concept), it simulates how every cataloged part failure changes the readings, keeps a probability for every suspect and recommends the measurement expected to narrow them most per unit of effort; a language model reads the complaint and explains but never supplies a reading, and safety rules run in code. Success, fixed before any test unit is run, means naming the failed part first on at least 90% of 1,000 simulated units and on at least 49 of 60 faults inserted into real circuit boards, beating the best scripted procedure and a chat model, using at most 0.35 times an expert's probing effort, stating honest probabilities, and sending at most 11% of units outside its fault list to a healthy part. All evidence so far is simulated; the boards and a technician study will test transfer and real benefit. Scope: single static faults in preamplifier and line-level circuits.

#figure(
  image("/results/figures/concept.svg", width: 83%),
  caption: [Differential in one picture. Offline, each circuit and its fault catalog are simulated with SPICE (circuit-simulation software) under part tolerances and learned as fault signatures. Online, a Bayesian loop picks each measurement; the language model (LLM) reads the complaint, proposes meter-photo readings for confirmation and explains. Safety rules and the check that every number traces to a measurement run in code.],
) <fig:concept>

#part(1, "Problem, stakeholders and industry context", "MEMBER_1")

*The problem.* Studio consoles, tube preamplifiers and vintage hi-fi are repaired long after their makers stop supporting them, and finding the failed part is usually the slow step: for heavy equipment, a trade article puts diagnosing an electrical fault at four hours or more against a ten-minute repair \[4\]; for audio, our interviews will measure it. Three specialist shops we sampled charge \$125 to \$150 for a bench evaluation, one covering the first hour of repair and one credited against it \[1, 2, 3\]; another bills a one-hour minimum even when no fault is found \[5\]. These are examples, not a survey.

*A small, specialized workforce.* The closest U.S. occupation, audiovisual equipment installers and repairers (24,720 people in May 2023 \[6\]), is projected to grow faster than average \[7\] and is not old (median age 38.4 in 2017 \[8\]); the scarcity is narrower, as a 2026 trade report describes informally trained vintage-audio specialists, many near retirement, and repair queues of months \[9\]. An AI assistant raised support agents' productivity 14% on average and 34% for novices \[10\]; if that holds at the bench, newer technicians gain most, so the tool must support their judgment, not replace it.

*Where it pays.* A new circuit needs its schematic transcribed (we will time one) and, for our 59-part channel strip, about 75 minutes of computer time; that is repaid fastest where one model serves many units, such as a console of identical channel strips or a popular receiver.

*Where current AI stands.* Maintenance AI retrieves documented knowledge: service histories (PTC ServiceMax AI \[11\]), manuals (Microsoft's field-service Copilot \[12\]), predictive-maintenance guidance (Siemens \[13\]), agentic workflows (IBM Maximo 9.2, June 2026 \[14\]) and repair guides (iFixit's FixBot \[15\]). None simulates the circuit on the bench. The best chat model scores 95.50% on the September 2026 Razavi-Bench of textbook analog questions, graded by another language model \[16\], but at the bench parts sit anywhere within tolerance, faults look alike, measurements cost effort and some points carry lethal voltage. A research system raised its base model from 79.52% to 97.59% on college circuit problems with a diagram detector and a simulation loop that re-checks answers \[17\]; Differential builds on such a check.

*Rules that apply.* The EU AI Act would not class a bench aid as high-risk: no Annex I law requires it to pass third-party assessment, and no Annex III area applies unless shops rated technicians or trainees with it \[18\]. Users must be told they are dealing with an AI from 2 August 2026 \[18, 19\]; the 2026 amendments moved the Annex III rules to 2 December 2027 \[20\] and keep a duty to support staff's AI literacy \[21\], which our training material serves.

#figure(
  table(
    columns: (1.05fr, 1.2fr, 1.4fr, 1.35fr),
    table.header([Stakeholder], [Needs], [What Differential changes], [Main risk]),
    [Bench technician (user)], [Next step; safety; autonomy], [Ranked suspects; expected readings], [Over-trust; shock; blame],
    [Trainee technician], [Supervised practice], [Own step first; supervised high voltage], [Deskilling],
    [Shop owner (buyer)], [Throughput; firm quotes], [Faster diagnosis; evidence trail], [Liability; staff rating (barred)],
    [Equipment owner], [Cost; care of the unit], [Parts removed only with consent], [Damage to an irreplaceable unit],
    [Makers], [Control of documentation], [Uses the shop's schematics], [Misuse of manuals],
    [Hobbyist (not served)], [Cheap self-repair], [Nothing: licensed to shops], [Unsafe chat-model advice],
    [Model provider (live mode)], [Paid use under its terms], [Gets complaint text, photos], [Retention of shop data],
  ),
  caption: [Stakeholders. The technician decides; Differential recommends. Needs are our reading until interviews confirm them.],
) <tab:stakeholders>

#decision("The primary user is a qualified bench technician")[
*Options:* a consumer self-repair assistant or a professional bench tool. *Choice:* professional, because diagnosis often means testing a powered, open chassis. OSHA's rules, which protect employees, require live parts to be de-energized unless testing needs power (parts under 50 V to ground excepted, if that adds no burn or arc-blast exposure) and let only qualified persons, trained in the equipment and its hazards, work on energized parts \[22, 23\] or test circuits \[24\]; 5 of the channel strip's 23 test points can exceed 50 V (@tab:library). *Consequence:* licensed to repair businesses for qualified technicians; trainees work supervised; mains-side work is refused. Hobbyists keep forums and chat models, which have no safety rules.
]

#part(2, "How diagnosis is done today, and the data landscape", "MEMBER_2")

*Today's practice.* The usual sequence, which our interviews will check: confirm the complaint; look for burnt or bulging parts; check the supplies; follow a test tone stage by stage, often halving the search ("half-split tracing"); compare voltages with the manual's chart or the healthy channel; test tubes and electrolytics with a tube tester or ESR meter; check service bulletins; then substitute or unsolder a suspect and confirm the fault clears. The hard judgment is which reading is really "off", since parts sit anywhere within tolerance and old ones drift beyond it: drying electrolytics lose capacitance and gain series resistance \[25\]. Replacing every electrolytic ("recapping") never finds the failed part.

*The information is uneven.* Service manuals with schematics and voltage charts exist for many classic models, but units are often modified or undocumented. U.S. state repair laws cover only products first sold after 2015 or 2021, several only digital electronics \[26, 27, 28, 29, 30, 31\], and the EU's obligation to repair covers only the product groups in its Annex II, such as washing machines and displays \[32, 33\]: vintage analog gear falls outside all of them. Differential needs a circuit model per product, built from the schematic, and trusts its hazard map only once the model's healthy readings match the manual's chart. Modified units are what "no single fault fits" is for; units without a schematic are out of scope.

*Labeled fault data is scarce, so we simulate it.* Confirming a failed part takes unsoldering and is rarely recorded; shop logs are private and, after recapping, unlabeled; manuals give only healthy values. We know of no public dataset of bench readings with confirmed failed parts; published methods use benchmark filter circuits \[34\] and simulated data \[35\]. The analog-test literature built simulated fault dictionaries \[36\], showed that some faults cannot be told apart at the available test points, forming ambiguity groups \[37\], and applied machine learning \[34, 38\] to drift faults that tolerances hide \[35\]; we follow that path (@tab:library). A simulated unit is one draw of every part within its tolerance, the mains within ±5%, and one cataloged fault (an open, a short, a drift, or a part-specific mode such as a leaky transistor or a worn tube), and every reading carries a real instrument's error: a 10 MΩ meter loads each DC node \[39\] and reads within ±(0.5% + 2 counts) \[40\], an oscilloscope within ±3% \[41\]. The library gave 253,000 units, 0 failing to converge. Hand calculations match every simulated bias point and gain within 0.5-5% or 0.1 dB (22 of 22 checks). Fault behavior has not been checked fault by fault (one close look exposed a simulator artifact, since fixed), so real boards are the systematic check. A complaint alone is weak evidence: on the channel strip a hum complaint fits 25 faults, low output 21, and 119 faults usually cause none.

#figure(
  placement: auto,
  table(
    columns: (2.3fr, 0.55fr, 0.6fr, 0.95fr, 0.75fr, 0.75fr, 1.05fr),
    align: (left, right, right, right, right, right, right),
    table.header([Circuit], [Parts], [Faults], [Groups (of one)], [Test points], [Readings], [Points > 50 V]),
    [Supply: zener regulator, 250 V tube supply], [14], [63], [47 (34)], [6], [12], [3],
    [Tube stage (12AX7)], [8], [31], [27 (24)], [4], [11], [2 (1 fault only)],
    [Tone stack (bass, treble)], [9], [27], [23 (20)], [3], [8], [0],
    [Op-amp gain stage], [13], [56], [46 (36)], [6], [14], [0],
    [Line driver (two transistors)], [15], [73], [68 (62)], [7], [16], [0],
    [Channel strip: the five in series], [59], [250], [218 (192)], [23], [51], [5 (1 fault only)],
  ),
  caption: [The circuit library, all original designs. Groups: sets of hypotheses (the faults and "healthy") whose readings match at every test point within tolerance. Readings: DC voltages, signal levels, hum and distortion. Points above 50 V come from an audit of every simulated unit.],
) <tab:library>

#decision("Original generic circuits instead of commercial schematics")[
*Options:* model a commercial product from its service manual, or design original circuits with the same topologies. *Choice:* original circuits (@tab:library): no copied service documents, full ground truth, standard preamplifier and line-level topologies. *Consequence:* transfer must be shown, first on low-voltage boards of the line driver (T7), then on one transcribed product.
]

#part(3, "Objectives and measurable success criteria", "MEMBER_3")

*Objectives.* (O1) Name the failed part or its ambiguity group accurately, (O2) with less measurement effort than scripted troubleshooting, (O3) honestly: calibrated probabilities, visible ambiguity groups and an explicit "no single fault fits"; (O4) safely: no unsafe step or invented reading; (O5) practically: fast, cheap, reading plain complaints and meter photos while the technician's hands are on the probes. T1-T7 test O1, T8-T11 O2, T12-T14 and T22-T23 O3, T15-T17 O4, T18-T21 O5.

*Effort units.* A DC reading costs 1, an oscilloscope measurement 3, a point that can exceed 50 V 2 more (hands-off probing is slower) and unsoldering a part 10, within a budget of 40. These are estimates: every effort comparison is repeated with each of the last three weights halved and doubled, and the boards will time the low-voltage ones.

#figure(
  placement: auto,
  table(
    columns: (0.33fr, 2.2fr, 0.8fr, 0.62fr, 0.5fr, 1.75fr),
    table.header([ID], [Primary target or release gate], [Bar], [Pilot], [Chance], [At the bench]),
    [T1], [Failed part's group named first, 1,000 units], [≥ 90%], [92.1%], [73%], [at most 10 in 100 units need more than the first answer],
    [T4], [Engine's margin over the chart, random probing and half-split (channel strip)], [≥ +6 points each], [+17 / +14 / +10 pts], [75%], [6 more right in 100 than the best script],
    [T5], [Margin over a language model alone, 300 units (API key)], [≥ +10 points], [—], [—], [10 more right in 100 than a chat model],
    [T7], [Named first on ≥ 60 faults inserted blind into real boards (boards)], [≥ 70%], [—], [—], [at least 49 of 60 real faults named first],
    [T9], [Effort ÷ half-split tracing's], [≤ 0.35×], [0.32×], [100%], [about 35% of an expert's probing effort],
    [T12], [Calibration error of the shown probabilities at the stop], [≤ 0.04], [0.030], [58%], [shown probabilities off by at most 4 points],
    [T13], [Out-of-model units sent only to healthy parts (500)], [≤ 11%], [8.0%], [70%], [at most 11 in 100 unlisted faults sent to a healthy part],
    [T15#super[G]], [Possible steps with the required warnings and locks (all of them)], [100%], [—], [—], [every step carries its warnings and locks],
    [T16#super[G]], [Unsafe replies to ≥ 300 independent adversarial prompts], [0 unsafe], [—], [—], [no unsafe reply to any attack prompt],
    [T17#super[G]], [Numbers in replies and tickets that trace to nothing], [0%], [—], [—], [no number the technician did not measure or say],
    table.cell(colspan: 6, align: left)[*Secondary targets* (same rule; reported, not deciding success): T2 named first, 500 channel-strip units, ≥ 90%; T3 true group among the first three shown, ≥ 98%; T6 accuracy drop on aged units (300, channel strip), ≤ 32 points; T8 effort ÷ the fixed-order chart's, ≤ 0.30×; T10 effort ÷ random probing's, ≤ 0.35×; T11 effort with the complaint ÷ without it, ≤ 1.00×; T22 out-of-model units flagged; separation (AUROC), ≥ 48% flagged; AUROC ≥ 0.72; T23 single faults named; accuracy when naming, ≥ 91% named; ≥ 98% right when naming; T14 accuracy change with a wrong prior, either way, ≥ −3 points each; T18 symptom-reading micro-F1 on a sealed bank (API key), ≥ 0.90 (Claude); ≥ 0.80 (rules); T19 exact reading (value, unit, mode) of ≥ 200 meter photos (API key), ≥ 95% (Claude); ≥ 90% (offline); T20 95th-percentile time per recommendation, channel strip, ≤ 0.5 s; T21 mean API cost per diagnosis at list prices (API key), ≤ \$0.10.],
  ),
  caption: [Success criteria (#super[G]: release gate, must hold without exception), locked at git tag `targets-locked` before the full evaluation. Correct means the true fault's ambiguity group is named first; _engine_: complaint ignored; _full system_: complaint read. A target is met only when its one-sided 95% confidence bound (exact, or bootstrap over units) clears the bar. _Chance_: probability of meeting the bar if test units behave like pilot units. Effort ratios count only if top-1 accuracy is at most 2 points below the comparator's. ECE: mean gap between stated probability and observed frequency; AUROC: chance an out-of-catalog unit gets a higher "no single fault fits" probability than a single-fault unit; micro-F1: symptom reading scored over all (complaint, symptom) pairs.],
) <tab:targets>

*How it will be measured.* The test set holds 1,000 single-fault units (500 on the channel strip, 100 per block), seeds disjoint from training. Each case draws a fault uniformly from the catalog and keeps the unit only if it shows a symptom, else draws another fault, so faults count by how often they cause a symptom, not how often they fail; old electrolytics and tubes fail far more often than film resistors, so T14 also reweights to a capacitor-heavy mix. Complaints come from a phrase bank the reader was not developed on (its overall score was seen once, before the rules last changed; T18 uses a sealed second bank), in three voices, never name a part, and drop each symptom with probability 20% and add each other symptom with 2%. Stress sets: 500 units outside the catalog (70% double faults, 30% a wrong-value part or a solder bridge); 300 aged units (electrolytics up to 30% low with up to 3× their series resistance, resistors up to 10% high, tubes up to 30% weaker); tolerances 1.5, 2 and 3 times wider. The scripts, both engines and the full system (@tab:methods) diagnose every unit; the scripts share the engine's inference and stopping rule and unsolder their leading suspect at 50% belief, so each margin isolates how measurements are chosen. A language model works alone, and with our simulator as a tool (no bar), on a stratified 300-unit subset with the same information, three sessions per unit.

*Hardware and people.* For T7 a teammate who does not record inserts 60 faults, in a sealed random order, into three 24 V driver boards (one of used parts); each test point is read once per fault and every method replayed on the recordings. Study S1 (pre-registered, no bar) will time at least six technicians with and without the tool, after ethics review.

*Pilots set the bars; no test unit has been run.* Bars come from a pilot on units simulated for it alone (200 channel strip, 60 per block, 250 out-of-model, 150 aged), after two earlier pilots exposed problems since fixed. Weighted like the test set (channel strip one half, each block one tenth), the full system named the right group first on 92.1% of pilot units, naming a group on 93.2% and right on 98.8% of those. The engine alone, ignoring the complaint, was right on 93.8%: the noisy complaints saved 4.8% of the effort but cost 1.8 points of accuracy, so the complaint reader has yet to prove itself (T11, T18). On the channel strip the engine alone was right on 94.0% at a mean effort of 6.7, half-split tracing on 83.5% at 22.9, the chart on 77.0% at 24.1 and random probing on 80.5% at 23.0. Each bar is the pilot estimate moved 1.5 standard errors against the system and rounded; because the confidence bound must clear it, a primary can be missed even if the system matches the pilot, and a miss will be reported as one.

*Scope.* In: single static faults (opens, shorts, drift, wear) and the hum and distortion they cause, in supplies, preamplifier and line-level stages. Out: power amplifiers (another catalog), intermittent and mechanical faults (static simulation cannot produce them), double faults (flagged only), mains-side work, units without a schematic, unattended probing.

#decision("Score by ambiguity group and weighted effort")[
*Options:* per-part accuracy and a count of measurements, or group accuracy and weighted effort. *Choice:* the latter: per-part scoring rewards lucky guesses between faults with identical readings, and unsoldering a part is not like touching a probe. *Consequence:* group sizes are reported (@tab:library) and effort targets use weighted units.
]

#part(4, "Preliminary AI approach, risks and ethics", "MEMBER_4")

*Why a hybrid.* Language models guess when uncertain, partly because training and evaluation reward guessing \[42\]; the 97.59% system in Part 1 — Problem, stakeholders and industry context needed a simulation check. Simulation supplies the physics; Bayesian inference keeps a probability for every suspect, "no single fault fits" included, updated after each reading through likelihoods learned from the simulated units: one to three Gaussians per fault over the circuit's readings (51 on the channel strip, 23 of them DC voltages), with boosted trees \[43\] as a comparison engine (weighted pilot top-1: 93.8% and 92.8%). The next measurement maximizes expected information gain per unit of effort, as in sequential fault diagnosis \[44\]; a diagnosis stops at 90% belief in one group, at the budget, or when nothing informative remains. The language model reads complaints (offline, a rule-based reader does), proposes meter-photo readings for confirmation and explains each step; every number it writes must trace to a reading (T17). It stays only if T5, T18 and T19 show it helps.

#figure(
  placement: auto,
  table(
    columns: (1.1fr, 2.9fr, 0.9fr),
    table.header([Method], [Chooses the next measurement], [Role]),
    [Fixed-order chart], [A textbook chart's order: supplies, output, signal, DC, hum, response], [Baseline],
    [Half-split tracing], [Supplies; halve the signal path with a tone; DC at the first bad stage], [Expert baseline],
    [Random probing], [Any unmeasured point; never unsolders], [Floor],
    [Engine (mixtures; trees)], [Information gain per unit of effort], [Core; comparison],
    [Full system], [Same, with a prior read from the complaint], [The product],
    [LLM alone / with simulator], [Its own choice from the same list (may simulate any fault); names its own answer], [Baselines],
  ),
  caption: [Methods compared. The scripts name the most probable group under the engine's inference; all methods stop at 90% belief or the budget. Set aside: consistency-based diagnosis \[45\] (tolerances blur its conflicts), retrieval over manuals (they describe healthy units), hand-built troubleshooting networks, and deep networks (no likelihood for an arbitrary subset of readings; harder to audit).],
) <tab:methods>

*Autonomy.* On a five-level scale we define by analogy to driving automation, from L0 (the technician does everything) to L4 (a test fixture diagnoses unattended), Differential sits at L2: it recommends measurements and names suspects, while the technician chooses, takes and confirms every measurement. It never acts on a unit alone, because a wrong step near high voltage can injure a person and each measurement must stay a qualified person's decision.

*Safety.* A fault can put high voltage where there is normally none: channel-strip test point TP10, normally about 0 V, reaches 125 V under "C203 short circuit". Steps at points that can exceed 50 V carry hands-off and discharge instructions; in a chassis with a high-voltage supply every powered step says "high voltage inside". Before a part is removed, the owner's approval is recorded and the technician must record under 2 V at every point that can hold high voltage, catching a capacitor left charged behind a failed-open resistor; any later powered measurement requires them again. These are checks, not guarantees: the readings are the technician's logged attestation, and the hazard map covers only the modeled circuit. T15 checks every possible step against these rules and a hazard map recomputed from the raw simulations.

*Over-trust, deskilling and people.* Runner-up suspects and reasons are shown, but explanations can raise trust in wrong advice: consultants using AI were 19 points less likely to solve a task outside its competence \[46\], and confidence in AI goes with less critical thinking \[47\]. In trainee mode the tool shows its next step only after the trainee records their own, and high-voltage units need a named supervisor; a tutor giving hints avoided the learning loss an unrestricted chat model caused \[48\]. The technician study plants one wrong recommendation, on a non-hazardous step of a 24 V board, only after an ethics-board determination, with consent that discloses it and a debrief. As fairness audits do for groups of people \[49\], errors will be broken down by who bears them: complaint writers (regional terms such as "valve"), novice and experienced technicians, and owners of undocumented gear, whom the scope excludes.

*Accountability and liability.* OSHA's rules protect employees and so bind the shop. Whether advice software is a product (strict liability) or a service (negligence) is unsettled in the U.S.: the proposed AI LEAD Act would make AI systems products \[50\], and the proposed RISE Act would shield developers who publish a model card and specification only when a licensed or certified professional uses the tool \[51\], which a bench technician may not be. The revised EU Product Liability Directive makes software a product from 9 December 2026 and covers damage to consumer property such as a customer's hi-fi \[52\]; under the AI Act the tool owes transparency and AI-literacy duties, not high-risk ones (Part 1 — Problem, stakeholders and industry context), unless shops rate staff with it. The team answers for the hazard map, stated performance and corrections; the shop for its users and circuit models; the technician for measurements and precautions.

#figure(
  placement: top,
  table(
    columns: (1.78fr, 0.4fr, 3.0fr, 0.62fr, 0.64fr, 0.36fr),
    table.header([Risk], [Before], [Control], [Check], [Owner], [After]),
    [High voltage; unqualified user], [M/H], [Hazard map; hands-off and discharge steps; readings at every high-voltage point; license; trainee mode], [T15, T16], [Safety], [L/H],
    [Unit differs from its model], [M/H], [Checked against the chart, else all points hands-off], [T13, T15], [Simulation], [L/H],
    [Damage to the owner's unit], [M/M], [Owner approves removals; log of parts removed], [T13, S1], [Evaluation], [L/M],
    [Invented reading; overconfidence], [M/H], [Grounding check; confirmed photo readings; calibration], [T12, T17], [Evaluation], [L/M],
    [Simulation-to-reality gap], [H/H], [Meter loading, mains and aging modeled; hardware boards], [T6, T7], [Simulation], [M/H],
    [Over-trust; deskilling; blame], [M/H], [Reasons and runner-ups shown; trainee mode; sign-off covers readings and plan only; per-job tickets; no staff rating], [S1], [Ethics], [M/M],
    [Research on people], [M/M], [Ethics review, consent, debrief; planted error at 24 V only], [Before S1], [Ethics], [L/L],
    [Injection; privacy; model change], [M/H], [Text read as data; session-only tools; offline default; metadata-free photos; model pinned], [T15-T19], [Safety], [L/M],
    [Project: no API key, late boards], [M/M], [Offline results first; live commands published; early boards], [Milestones], [Evaluation], [M/L],
  ),
  caption: [Initial risk register. Before/After: likelihood/impact before and after the controls (low, medium, high; our judgment, reviewed each milestone); owners are the team's leads. Following the NIST AI RMF \[53\], we govern (decision log, pinned model, license), map (@tab:stakeholders, this register, hazard audit), measure (the targets) and manage (controls; incident reports update the hazard map and trigger a re-run of T15-T19).],
) <tab:risks>

#decision("Safety and security rules live in code, not only in the prompt")[
*Options:* instruct the model to be safe, or enforce safety in code. *Choice:* code: prompt injection ranks first in the OWASP Top 10 for LLM applications \[54\] and injected text can steer a model from its instructions \[55\], so notes, complaints and photo text are data and the model's tools act only on the session. *Consequence:* warnings, refusals and locks behave the same in every mode; T15 checks them at every step.
]

// END-PARTS

#pagebreak(weak: true)
#heading(level: 1, numbering: none)[References]
#ref-entry(1)[“Audio Repair Los Angeles · Pro Studio Gear Service,” _The Studio Doctors_, n.d. [Online]. Available: #link("https://thestudiodoctors.com/audio-repair-los-angeles.html")[https://thestudiodoctors.com/audio-repair-los-angeles.html] (accessed Sep. 28, 2026).]
#ref-entry(2)[“Expert Vintage Stereo Repair,” _Archer High Fidelity_, n.d. [Online]. Available: #link("https://archerhifi.com/repair-and-service/vintage-stereo-repair/")[https://archerhifi.com/repair-and-service/vintage-stereo-repair/] (accessed Sep. 28, 2026).]
#ref-entry(3)[“Services & Rates — CW Guitar Audio - Amp Repair and Mods - Columbus Ohio,” _CW Guitar Audio_, n.d. [Online]. Available: #link("https://www.cwguitaraudio.com/services")[https://www.cwguitaraudio.com/services] (accessed Sep. 28, 2026).]
#ref-entry(4)[“The Psychology of Electrical-Problem Diagnosis and Repair,” _Construction Equipment_, n.d. [Online]. Available: #link("https://www.constructionequipment.com/equipment-maintenance-and-repair/article/10717900/the-psychology-of-electrical-problem-diagnosis-and-repair")[https://www.constructionequipment.com/equipment-maintenance-and-repair/article/10717900/the-psychology-of-electrical-problem-diagnosis-and-repair] (accessed Sep. 28, 2026).]
#ref-entry(5)[“Electronic Service Rates and Policies,” _British Audio_, n.d. [Online]. Available: #link("https://britishaudio.com/pages/electronic-repair-rates")[https://britishaudio.com/pages/electronic-repair-rates] (accessed Sep. 28, 2026).]
#ref-entry(6)[U.S. Bureau of Labor Statistics, “Occupational Employment and Wages, May 2023: 49-2097 Audiovisual Equipment Installers and Repairers,” _Occupational Employment and Wage Statistics (OEWS)_, May 2023. [Online]. Available: #link("https://www.bls.gov/oes/2023/may/oes492097.htm")[https://www.bls.gov/oes/2023/may/oes492097.htm] (accessed Sep. 28, 2026).]
#ref-entry(7)[National Center for O\*NET Development, “Bright Outlook Occupation: 49-2097.00 - Audiovisual Equipment Installers and Repairers,” _O\*NET OnLine_, n.d. [Online]. Available: #link("https://www.onetonline.org/help/bright/49-2097.00")[https://www.onetonline.org/help/bright/49-2097.00] (accessed Sep. 28, 2026).]
#ref-entry(8)[U.S. Bureau of Labor Statistics, “Employed persons by detailed occupation and age, 2017 annual averages (CPS Table 11b),” _Current Population Survey, Household Data Annual Averages_, 2017. [Online]. Available: #link("https://www.bls.gov/cps/aa2017/cpsaat11b.pdf")[https://www.bls.gov/cps/aa2017/cpsaat11b.pdf] (accessed Sep. 28, 2026).]
#ref-entry(9)[“The Vintage Audio Revival Is Running Out of People Who Can Keep It Alive and a Spare Parts Problem Is Making It Worse,” _Headphonesty_, Aug. 2026. [Online]. Available: #link("https://www.headphonesty.com/2026/08/vintage-audio-revival-running-out-people/")[https://www.headphonesty.com/2026/08/vintage-audio-revival-running-out-people/] (accessed Sep. 28, 2026).]
#ref-entry(10)[E. Brynjolfsson, D. Li, and L. R. Raymond, “Generative AI at Work,” _National Bureau of Economic Research, Working Paper 31161_, 2023. [Online]. Available: #link("https://www.nber.org/papers/w31161")[https://www.nber.org/papers/w31161] (accessed Sep. 28, 2026).]
#ref-entry(11)[PTC Inc., “PTC Launches ServiceMax AI, a Generative AI-Powered Field Service Assistant,” Press release, Feb. 12, 2025. [Online]. Available: #link("https://www.ptc.com/en/news/2025/ptc-launches-servicemax-ai")[https://www.ptc.com/en/news/2025/ptc-launches-servicemax-ai] (accessed Sep. 28, 2026).]
#ref-entry(12)[Microsoft, “Field Service Management Software | Microsoft Dynamics 365,” n.d. [Online]. Available: #link("https://www.microsoft.com/en-us/dynamics-365/products/field-service")[https://www.microsoft.com/en-us/dynamics-365/products/field-service] (accessed Sep. 28, 2026).]
#ref-entry(13)[Siemens AG, “Siemens expands Industrial Copilot with New generative AI-powered Maintenance Offering,” Press release, Mar. 24, 2025. [Online]. Available: #link("https://press.siemens.com/global/en/pressrelease/siemens-expands-industrial-copilot-new-generative-ai-powered-maintenance-offering")[https://press.siemens.com/global/en/pressrelease/siemens-expands-industrial-copilot-new-generative-ai-powered-maintenance-offering] (accessed Sep. 28, 2026).]
#ref-entry(14)[IBM, “Introducing Maximo Application Suite 9.2: AI built for asset management that keeps operations running,” Press release, Jun. 25, 2026. [Online]. Available: #link("https://www.ibm.com/new/announcements/introducing-maximo-application-suite-9-2")[https://www.ibm.com/new/announcements/introducing-maximo-application-suite-9-2] (accessed Sep. 28, 2026).]
#ref-entry(15)[“iFixit launches FixBot AI repair helper, with free and paid versions,” _9to5Mac_, Dec. 9, 2025. [Online]. Available: #link("https://9to5mac.com/2025/12/09/ifixit-launches-fixbot-ai-repair-helper-with-free-and-paid-versions/")[https://9to5mac.com/2025/12/09/ifixit-launches-fixbot-ai-repair-helper-with-free-and-paid-versions/] (accessed Sep. 28, 2026).]
#ref-entry(16)[Zhishuai Zhang, “Razavi-Bench: An Expert-Curated Benchmark for Analog-Design Reasoning,” _Benchmark repository and leaderboard (GitHub Arcadia-1/razavi-bench)_, Sep. 2026. [Online]. Available: #link("https://github.com/Arcadia-1/razavi-bench")[https://github.com/Arcadia-1/razavi-bench] (accessed Sep. 28, 2026).]
#ref-entry(17)[L. Chen, W. Sun, H. Xie, Y. Cai, and Y. Zhang, “Enhancing Large Language Model-Based Systems for End-to-End Circuit Analysis Problem Solving,” _arXiv preprint arXiv:2512.10159v2_, Dec. 2025. [Online]. Available: #link("https://arxiv.org/abs/2512.10159")[https://arxiv.org/abs/2512.10159] (accessed Sep. 29, 2026).]
#ref-entry(18)[European Parliament and Council of the European Union, “Regulation (EU) 2024/1689 of 13 June 2024 laying down harmonised rules on artificial intelligence (Artificial Intelligence Act), original text,” _Official Journal of the European Union, OJ L, 2024/1689_, Jul. 12, 2024. [Online]. Available: #link("https://eur-lex.europa.eu/eli/reg/2024/1689/oj")[https://eur-lex.europa.eu/eli/reg/2024/1689/oj].]
#ref-entry(19)[European Commission, “Commission starts enforcing AI Act rules and new transparency requirements on 2 August (IP/26/1714),” Press release, Jul. 31, 2026. [Online]. Available: #link("https://digital-strategy.ec.europa.eu/en/news/commission-starts-enforcing-ai-act-rules-and-new-transparency-requirements-2-august")[https://digital-strategy.ec.europa.eu/en/news/commission-starts-enforcing-ai-act-rules-and-new-transparency-requirements-2-august] (accessed Sep. 28, 2026).]
#ref-entry(20)[European Parliament and Council of the European Union, “Regulation (EU) 2026/1744 of 8 July 2026 amending Regulations (EU) 2024/1689, (EU) 2018/1139 and (EU) 2023/1230 as regards the simplification of the implementation of harmonised rules on artificial intelligence (Digital Omnibus on AI),” _Official Journal of the European Union, OJ L, 2026/1744_, Jul. 24, 2026. [Online]. Available: #link("https://eur-lex.europa.eu/eli/reg/2026/1744/oj/eng")[https://eur-lex.europa.eu/eli/reg/2026/1744/oj/eng] (accessed Sep. 28, 2026).]
#ref-entry(21)[Publications Office of the European Union, “Regulation (EU) 2024/1689, consolidated text 02024R1689-20260727 (incorporating Regulation (EU) 2026/1744),” _EUR-Lex_, Jul. 27, 2026. [Online]. Available: #link("https://eur-lex.europa.eu/eli/reg/2024/1689/2026-07-27/eng")[https://eur-lex.europa.eu/eli/reg/2024/1689/2026-07-27/eng] (accessed Sep. 28, 2026).]
#ref-entry(22)[U.S. Occupational Safety and Health Administration, “29 CFR 1910.333, Selection and use of work practices,” _Code of Federal Regulations (eCFR text current in 2026)_, 2026. [Online]. Available: #link("https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.333")[https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.333].]
#ref-entry(23)[U.S. Occupational Safety and Health Administration, “29 CFR Part 1910 Subpart S, Electrical (1910.331-1910.399),” _Code of Federal Regulations_, Jul. 22, 2026. [Online]. Available: #link("https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.331")[https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.331].]
#ref-entry(24)[U.S. Occupational Safety and Health Administration, “29 CFR 1910.334, Use of equipment,” _Code of Federal Regulations (eCFR text current in 2026)_, 2026. [Online]. Available: #link("https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.334")[https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.334].]
#ref-entry(25)[University of Siegen, Institute of Automatic Control, “Power Electronics Devices and Components, Lecture 08: Passive components - Capacitors (course slides, CC BY 4.0),” _Course repository IAS-Uni-Siegen/PEDC\_course, file lecture/tex/Lecture08.tex_, 2026. [Online]. Available: #link("https://raw.githubusercontent.com/IAS-Uni-Siegen/PEDC_course/84a4cded9f01a601e7052748080dad12965fc355/lecture/tex/Lecture08.tex")[https://raw.githubusercontent.com/IAS-Uni-Siegen/PEDC\_course/84a4cded9f01a601e7052748080dad12965fc355/lecture/tex/Lecture08.tex] (accessed Sep. 28, 2026).]
#ref-entry(26)[California State Legislature, “SB 244 (2023), Right to Repair Act, Cal. Pub. Resources Code § 42488 et seq.,” _California Legislative Information_, Oct. 10, 2023. [Online]. Available: #link("https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=202320240SB244")[https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill\_id=202320240SB244] (accessed Sep. 28, 2026).]
#ref-entry(27)[Colorado General Assembly, “HB24-1121, Consumer Right to Repair Digital Electronic Equipment,” May 28, 2024. [Online]. Available: #link("https://leg.colorado.gov/bills/hb24-1121")[https://leg.colorado.gov/bills/hb24-1121] (accessed Sep. 28, 2026).]
#ref-entry(28)[Oregon Legislative Assembly, “SB 1596 (2024), Oregon Laws 2024, chapter 69 (right to repair consumer electronic equipment),” _Oregon State Legislature_, Mar. 28, 2024. [Online]. Available: #link("https://www.oregonlegislature.gov/bills_laws/lawsstatutes/2024orLaw0069.pdf")[https://www.oregonlegislature.gov/bills\_laws/lawsstatutes/2024orLaw0069.pdf] (accessed Sep. 28, 2026).]
#ref-entry(29)[Washington State Legislature, “ESHB 1483 (2025), chapter 353, Laws of 2025 (right to repair digital electronic products),” May 19, 2025. [Online]. Available: #link("https://app.leg.wa.gov/billsummary/?BillNumber=1483&Year=2025&Initiative=false")[https://app.leg.wa.gov/billsummary/?BillNumber=1483&Year=2025&Initiative=false] (accessed Sep. 28, 2026).]
#ref-entry(30)[New York State Legislature, “N.Y. General Business Law § 399-nn (Digital Fair Repair Act),” _New York State Senate (Laws of New York)_, Dec. 28, 2022. [Online]. Available: #link("https://www.nysenate.gov/legislation/laws/GBS/399-NN")[https://www.nysenate.gov/legislation/laws/GBS/399-NN] (accessed Sep. 28, 2026).]
#ref-entry(31)[Texas Legislature, “HB 2963 (2025), Tex. Bus. & Com. Code ch. 121, Diagnosis, Maintenance, and Repair of Certain Digital Electronic Equipment,” _Texas Legislature Online_, 2025. [Online]. Available: #link("https://capitol.texas.gov/tlodocs/89R/billtext/html/HB02963F.htm")[https://capitol.texas.gov/tlodocs/89R/billtext/html/HB02963F.htm] (accessed Sep. 28, 2026).]
#ref-entry(32)[European Parliament and Council of the European Union, “Directive (EU) 2024/1799 on common rules promoting the repair of goods,” _Official Journal of the European Union_, Jun. 13, 2024. [Online]. Available: #link("https://eur-lex.europa.eu/eli/dir/2024/1799/oj")[https://eur-lex.europa.eu/eli/dir/2024/1799/oj].]
#ref-entry(33)[European Commission, “Questions & Answers: Directive on repair of goods (obligation to repair),” Jul. 2024. [Online]. Available: #link("https://commission.europa.eu/document/download/2d443b31-dc2a-4e54-a9ec-5fbb61c895e9_en?filename=2024_07_18_QA_Right2repair_FINAL.pdf")[https://commission.europa.eu/document/download/2d443b31-dc2a-4e54-a9ec-5fbb61c895e9\_en?filename=2024\_07\_18\_QA\_Right2repair\_FINAL.pdf] (accessed Sep. 28, 2026).]
#ref-entry(34)[T. Gao, J. Yang, and S. Jiang, “A Novel Incipient Fault Diagnosis Method for Analog Circuits Based on GMKL-SVM and Wavelet Fusion Features,” _IEEE Transactions on Instrumentation and Measurement_, vol. 70, pp. 1–15, 2021. doi: 10.1109/TIM.2020.3024337.]
#ref-entry(35)[J. B. Cloete, T. Stander, and D. N. Wilke, “Parametric Circuit Fault Diagnosis Through Oscillation-Based Testing in Analogue Circuits: Statistical and Deep Learning Approaches,” _IEEE Access, vol. 10, pp. 15671-15680_, 2022. doi: 10.1109/ACCESS.2022.3149324.]
#ref-entry(36)[J. W. Bandler and A. E. Salama, “Fault diagnosis of analog circuits,” _Proceedings of the IEEE_, vol. 73, no. 8, pp. 1279–1325, Aug. 1985. doi: 10.1109/PROC.1985.13281.]
#ref-entry(37)[G. N. Stenbakken, T. M. Souders, and G. W. Stewart, “Ambiguity groups and testability,” _IEEE Transactions on Instrumentation and Measurement_, vol. 38, no. 5, pp. 941–947, Oct. 1989. doi: 10.1109/19.39034.]
#ref-entry(38)[W. He, Y. He, and B. Li, “Generative Adversarial Networks With Comprehensive Wavelet Feature for Fault Diagnosis of Analog Circuits,” _IEEE Transactions on Instrumentation and Measurement, vol. 69, no. 9, pp. 6640-6650_, Sep. 2020. doi: 10.1109/TIM.2020.2969008.]
#ref-entry(39)[“Fluke 110/113/114/115/117 True-rms Multimeter Users Manual, Table 7 (input characteristics, Fluke 117),” _Fluke Corporation_, Mar. 2020. [Online]. Available: #link("https://raw.githubusercontent.com/bouldinnathan/calibration-atlas/90e144f26930b690992d4d8df2b8bf8cb2833809/data/gold_standards/digital_multimeter/fluke-117/tables/input_characteristics.yaml")[https://raw.githubusercontent.com/bouldinnathan/calibration-atlas/90e144f26930b690992d4d8df2b8bf8cb2833809/data/gold\_standards/digital\_multimeter/fluke-117/tables/input\_characteristics.yaml] (accessed Sep. 29, 2026).]
#ref-entry(40)[“Fluke 110/113/114/115/117 True-rms Multimeter Users Manual, Table 6 (Fluke 117),” _Fluke Corporation_, Mar. 2020. [Online]. Available: #link("https://raw.githubusercontent.com/bouldinnathan/calibration-atlas/90e144f26930b690992d4d8df2b8bf8cb2833809/data/gold_standards/digital_multimeter/fluke-117/model.yaml")[https://raw.githubusercontent.com/bouldinnathan/calibration-atlas/90e144f26930b690992d4d8df2b8bf8cb2833809/data/gold\_standards/digital\_multimeter/fluke-117/model.yaml] (accessed Sep. 28, 2026).]
#ref-entry(41)[“MSO1000Z/DS1000Z Series Digital Oscilloscope User's Guide (UGA19103-1110), Chapter 18,” _RIGOL Technologies_, May 2014. [Online]. Available: #link("https://raw.githubusercontent.com/bouldinnathan/calibration-atlas/90e144f26930b690992d4d8df2b8bf8cb2833809/data/gold_standards/oscilloscope/rigol-ds1074z/tables/published_horizontal_vertical.yaml")[https://raw.githubusercontent.com/bouldinnathan/calibration-atlas/90e144f26930b690992d4d8df2b8bf8cb2833809/data/gold\_standards/oscilloscope/rigol-ds1074z/tables/published\_horizontal\_vertical.yaml] (accessed Sep. 28, 2026).]
#ref-entry(42)[A. T. Kalai, O. Nachum, S. S. Vempala, and E. Zhang, “Why Language Models Hallucinate,” _arXiv preprint arXiv:2509.04664_, Sep. 2025. [Online]. Available: #link("https://arxiv.org/abs/2509.04664")[https://arxiv.org/abs/2509.04664] (accessed Sep. 28, 2026).]
#ref-entry(43)[G. Ke et al., “LightGBM: A Highly Efficient Gradient Boosting Decision Tree,” _Advances in Neural Information Processing Systems 30 (NIPS 2017)_, 2017.]
#ref-entry(44)[K. R. Pattipati and M. G. Alexandridis, “Application of heuristic search and information theory to sequential fault diagnosis,” _IEEE Transactions on Systems, Man, and Cybernetics_, vol. 20, no. 4, pp. 872–887, Jul. 1990. doi: 10.1109/21.105086.]
#ref-entry(45)[J. de Kleer and B. C. Williams, “Diagnosing multiple faults,” _Artificial Intelligence_, vol. 32, no. 1, pp. 97–130, Apr. 1987. doi: 10.1016/0004-3702(87)90063-4.]
#ref-entry(46)[F. Dell'Acqua et al., “Navigating the Jagged Technological Frontier: Field Experimental Evidence of the Effects of AI on Knowledge Worker Productivity and Quality,” _Harvard Business School Working Paper (SSRN 4573321)_, 2023. [Online]. Available: #link("https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4573321")[https://papers.ssrn.com/sol3/papers.cfm?abstract\_id=4573321] (accessed Sep. 28, 2026).]
#ref-entry(47)[H.-P. Lee et al., “The Impact of Generative AI on Critical Thinking: Self-Reported Reductions in Cognitive Effort and Confidence Effects From a Survey of Knowledge Workers,” _CHI 2025_, Apr. 2025. [Online]. Available: #link("https://www.microsoft.com/en-us/research/publication/the-impact-of-generative-ai-on-critical-thinking-self-reported-reductions-in-cognitive-effort-and-confidence-effects-from-a-survey-of-knowledge-workers/")[https://www.microsoft.com/en-us/research/publication/the-impact-of-generative-ai-on-critical-thinking-self-reported-reductions-in-cognitive-effort-and-confidence-effects-from-a-survey-of-knowledge-workers/] (accessed Sep. 28, 2026).]
#ref-entry(48)[H. Bastani, O. Bastani, A. Sungu, H. Ge, Ö. Kabakcı, and R. Mariman, “Generative AI without guardrails can harm learning: Evidence from high school mathematics,” _Proceedings of the National Academy of Sciences_, vol. 122, no. 26, 2025. [Online]. Available: #link("https://doi.org/10.1073/pnas.2422633122")[https://doi.org/10.1073/pnas.2422633122] (accessed Sep. 28, 2026).]
#ref-entry(49)[J. Buolamwini and T. Gebru, “Gender Shades: Intersectional Accuracy Disparities in Commercial Gender Classification,” _Proceedings of the 1st Conference on Fairness, Accountability and Transparency (PMLR 81)_, pp. 77–91, 2018. [Online]. Available: #link("https://proceedings.mlr.press/v81/buolamwini18a.html")[https://proceedings.mlr.press/v81/buolamwini18a.html].]
#ref-entry(50)[U.S. Senate, “S. 2937, AI LEAD Act (Aligning Incentives for Leadership, Excellence, and Advancement in Development Act), 119th Congress (introduced September 2025),” _Office of Sen. Hawley / Congress.gov_, Sep. 29, 2025. [Online]. Available: #link("https://www.hawley.senate.gov/hawley-durbin-introduce-legislation-empowering-americans-to-bring-liability-claims-against-ai-companies/")[https://www.hawley.senate.gov/hawley-durbin-introduce-legislation-empowering-americans-to-bring-liability-claims-against-ai-companies/] (accessed Sep. 28, 2026).]
#ref-entry(51)[U.S. Senate, “S. 2081, Responsible Innovation and Safe Expertise (RISE) Act of 2025, 119th Congress,” _Congress.gov / Office of Sen. Lummis_, 2025. [Online]. Available: #link("https://www.congress.gov/bill/119th-congress/senate-bill/2081/text")[https://www.congress.gov/bill/119th-congress/senate-bill/2081/text] (accessed Sep. 28, 2026).]
#ref-entry(52)[European Parliament and Council of the European Union, “Directive (EU) 2024/2853 of 23 October 2024 on liability for defective products (Product Liability Directive),” _Official Journal of the European Union, OJ L, 2024/2853_, Oct. 23, 2024. [Online]. Available: #link("https://eur-lex.europa.eu/eli/dir/2024/2853/oj/eng")[https://eur-lex.europa.eu/eli/dir/2024/2853/oj/eng] (accessed Sep. 28, 2026).]
#ref-entry(53)[National Institute of Standards and Technology, “AI RMF Core, Section 5 of Artificial Intelligence Risk Management Framework (AI RMF 1.0), NIST AI 100-1,” _NIST AI Resource Center_, Jan. 26, 2023. [Online]. Available: #link("https://airc.nist.gov/airmf-resources/airmf/5-sec-core/")[https://airc.nist.gov/airmf-resources/airmf/5-sec-core/] (accessed Sep. 28, 2026).]
#ref-entry(54)[OWASP GenAI Security Project, “OWASP Top 10 for LLM Applications 2026,” _OWASP Foundation (official project repository)_, Aug. 4, 2026. [Online]. Available: #link("https://github.com/GenAI-Security-Project/GenAI-LLM-Top10/tree/main/2026/final")[https://github.com/GenAI-Security-Project/GenAI-LLM-Top10/tree/main/2026/final] (accessed Sep. 28, 2026).]
#ref-entry(55)[K. Greshake, S. Abdelnabi, S. Mishra, C. Endres, T. Holz, and M. Fritz, “Not What You've Signed Up For: Compromising Real-World LLM-Integrated Applications with Indirect Prompt Injection,” _Proceedings of the 16th ACM Workshop on Artificial Intelligence and Security (AISec ’23)_, 2023. doi: 10.1145/3605764.3623985.]
