"""Fault-conditioned hazard map (generated by ``python -m eval.hv_audit``).

A test point is treated as high voltage when it exceeds 50 V in normal operation
("hv") or can exceed 50 V under any single catalog fault in the simulations
("hv_under_fault"). A reading never downgrades a point: a low reading at a
point that can carry B+ under a fault is not evidence that it is safe to touch.
Unknown points fail closed (treated as high voltage).

The map is only as good as the circuit model it was simulated from. A model that
has not been validated against an independent reference (hand calculations, or the
service manual's voltage chart for a transcribed product) could be wrong in exactly
the way that hides a hazard, so in a unit whose declared supply reaches 50 V every
point of an unvalidated model is treated as high voltage ("unvalidated_model",
ADR-034).
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Any

HV_MAP_PATH = Path(__file__).resolve().parent / "hv_map.json"
DISCHARGE_VERIFY_MAX_V = 2.0
HV_THRESHOLD = 50.0


@dataclass(frozen=True)
class Hazard:
    tp: str
    level: str  # "hv" | "hv_under_fault" | "lv" | "unknown"
    normal_max_v: float | None
    worst_case_v: float | None
    example_faults: tuple[str, ...]

    @property
    def high_voltage(self) -> bool:
        return self.level != "lv"


@lru_cache(maxsize=1)
def _map() -> dict[str, Any]:
    if not HV_MAP_PATH.exists():
        return {}
    return dict(json.loads(HV_MAP_PATH.read_text()))


def _unvalidated_hv(circuit_id: str) -> bool:
    """True when the circuit model is unvalidated and its declared supply is high voltage
    (or undeclared): every point is then treated as high voltage."""
    from differential.circuits.library import get_circuit

    try:
        c = get_circuit(circuit_id)
    except (KeyError, FileNotFoundError):
        return True
    if c.model_validated:
        return False
    return c.declared_supply_v is None or c.declared_supply_v >= HV_THRESHOLD


def hazard(circuit_id: str, tp: str) -> Hazard:
    info = _map().get(circuit_id, {}).get(tp)
    if _unvalidated_hv(circuit_id):
        return Hazard(tp, "unvalidated_model", None if info is None else float(info["normal_max_v"]),
                      None if info is None else float(info["worst_case_v"]), ())
    if info is None:
        return Hazard(tp, "unknown", None, None, ())
    return Hazard(tp, str(info["hazard"]), float(info["normal_max_v"]),
                  float(info["worst_case_v"]), tuple(info.get("example_faults", [])))


def needs_bring_up(circuit_id: str) -> bool:
    """A unit with a high-voltage supply or its own mains rectifier is first powered through
    a current limiter (ADR-042); boards on a low-voltage bench supply are not."""
    from differential.circuits.library import get_circuit

    if supply_voltage(circuit_id) is not None or _unvalidated_hv(circuit_id):
        return True
    try:
        return get_circuit(circuit_id).hum is not None
    except (KeyError, FileNotFoundError):
        return True


def supply_voltage(circuit_id: str) -> float | None:
    """Highest normal-operation voltage in the circuit when it is 50 V or more (the unit
    has a high-voltage supply), else None."""
    vals = [float(v["normal_max_v"]) for v in _map().get(circuit_id, {}).values()]
    top = max(vals, default=0.0)
    return top if top >= 50.0 else None


def circuit_has_hv(circuit_id: str) -> bool:
    return _unvalidated_hv(circuit_id) or any(
        v.get("hazard") != "lv" for v in _map().get(circuit_id, {}).values())


def discharge_points(circuit_id: str) -> list[str]:
    """Test points that must read below the discharge limit before hands-in work: every
    point that can hold high voltage in normal operation or under a fault (every point of
    an unvalidated high-voltage model)."""
    from differential.circuits.library import get_circuit

    c = get_circuit(circuit_id)
    return [tp.id for tp in c.test_points if hazard(circuit_id, tp.id).high_voltage]
