"""Fault-conditioned hazard map (generated by ``python -m eval.hv_audit``).

A test point is treated as high voltage when it exceeds 50 V in normal operation
("hv") or can exceed 50 V under any single catalog fault in the simulations
("hv_under_fault"). A reading never downgrades a point: a low reading at a
point that can carry B+ under a fault is not evidence that it is safe to touch.
Unknown points fail closed (treated as high voltage).
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Any

HV_MAP_PATH = Path(__file__).resolve().parent / "hv_map.json"
DISCHARGE_VERIFY_MAX_V = 2.0


@dataclass(frozen=True)
class Hazard:
    tp: str
    level: str  # "hv" | "hv_under_fault" | "lv" | "unknown"
    normal_max_v: float | None
    worst_case_v: float | None
    example_faults: tuple[str, ...]

    @property
    def high_voltage(self) -> bool:
        return self.level != "lv"


@lru_cache(maxsize=1)
def _map() -> dict[str, Any]:
    if not HV_MAP_PATH.exists():
        return {}
    return dict(json.loads(HV_MAP_PATH.read_text()))


def hazard(circuit_id: str, tp: str) -> Hazard:
    info = _map().get(circuit_id, {}).get(tp)
    if info is None:
        return Hazard(tp, "unknown", None, None, ())
    return Hazard(tp, str(info["hazard"]), float(info["normal_max_v"]),
                  float(info["worst_case_v"]), tuple(info.get("example_faults", [])))


def supply_voltage(circuit_id: str) -> float | None:
    """Highest normal-operation voltage in the circuit when it is 50 V or more (the unit
    has a high-voltage supply), else None."""
    vals = [float(v["normal_max_v"]) for v in _map().get(circuit_id, {}).values()]
    top = max(vals, default=0.0)
    return top if top >= 50.0 else None


def circuit_has_hv(circuit_id: str) -> bool:
    return any(v.get("hazard") != "lv" for v in _map().get(circuit_id, {}).values())
